// SPDX-License-Identifier: MIT
// @custom:security-contact bridge-security@alephzero.org

// ============================================================================
// FILE: Groth16Verifier.sol
// PURPOSE: On-chain verifier for Groth16 ZK-SNARK proofs. This contract
//          verifies proofs generated by the AlephBFT ZK circuit, which proves
//          that ≥2/3 of AlephBFT validators signed a finality commitment.
//
// BACKGROUND:
//   AlephBFT is a DAG-based BFT consensus protocol. Verifying its finality
//   proofs directly in Solidity would require checking N BLS signatures
//   (where N = committee size), costing millions of gas. Instead, we generate
//   a Groth16 ZK-SNARK proof off-chain that attests to the validity of these
//   signatures, and verify the compact proof on-chain for ~200-300k gas.
//
// CIRCUIT PUBLIC INPUTS (what the proof attests to):
//   [0] validatorSetHash  — keccak256 of the current validator public keys
//   [1] blockHash         — the AlephBFT block hash being finalized
//   [2] blockNumber       — the block height being finalized
//   [3] stateRoot         — the state root committed in this block
//
// MATH:
//   Groth16 verification uses bilinear pairings on the BN254 (alt_bn128) curve.
//   The verification equation is:
//     e(A, B) = e(alpha, beta) * e(sum_of_public_inputs, gamma) * e(C, delta)
//   where A, B, C are the proof elements and alpha, beta, gamma, delta are
//   the verification key elements (fixed at circuit compilation time).
//
// PRECOMPILES USED:
//   - 0x06: BN254 point addition (ecAdd)
//   - 0x07: BN254 scalar multiplication (ecMul)
//   - 0x08: BN254 pairing check (ecPairing)
// ============================================================================

// Solidity version pinned to 0.8.34 for production safety.
pragma solidity ^0.8.26;

/// @title Groth16Verifier
/// @notice Verifies Groth16 ZK-SNARK proofs for AlephBFT finality attestations.
/// @dev The verification key is hardcoded at deployment time. If the circuit
///      changes (e.g., validator set size changes), a new verifier must be deployed.
///      This is intentional — immutable verification keys prevent tampering.
contract Groth16Verifier {

    // ========================================================================
    // ERRORS
    // ========================================================================

    /// @notice Thrown when the pairing check precompile call fails.
    /// @dev This typically means the proof points are not on the curve,
    ///      or the precompile ran out of gas.
    error Groth16Verifier__PairingFailed();

    /// @notice Thrown when the scalar multiplication precompile call fails.
    error Groth16Verifier__ScalarMulFailed();

    /// @notice Thrown when the point addition precompile call fails.
    error Groth16Verifier__PointAdditionFailed();

    /// @notice Thrown when the number of public inputs doesn't match
    ///         what the circuit expects.
    error Groth16Verifier__InvalidInputCount();

    // ========================================================================
    // CONSTANTS — BN254 CURVE PARAMETERS
    // ========================================================================

    /// @notice The prime field modulus for BN254 (alt_bn128).
    /// @dev All arithmetic on G1 points is done modulo this prime.
    ///      This is the order of the base field Fp.
    uint256 internal constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @notice The order of the BN254 scalar field (Fr).
    /// @dev Public inputs must be reduced modulo this value.
    ///      This is the number of points on the elliptic curve.
    uint256 internal constant SCALAR_FIELD_ORDER = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ========================================================================
    // CONSTANTS — VERIFICATION KEY (from trusted setup ceremony)
    // ========================================================================
    // These values are generated during the Groth16 trusted setup ceremony.
    // They are specific to the AlephBFT finality circuit and CANNOT be changed
    // after deployment. Changing the circuit requires deploying a new verifier.
    //
    // IMPORTANT: The values below are PLACEHOLDERS. They must be replaced with
    // the actual verification key output from the trusted setup before deployment.
    // ========================================================================

    /// @notice Number of public inputs the circuit expects.
    /// @dev The AlephBFT finality circuit has 4 public inputs:
    ///      [0] validatorSetHash, [1] blockHash, [2] blockNumber, [3] stateRoot
    uint256 internal constant NUM_PUBLIC_INPUTS = 4;

    // --- Alpha point (G1) ---
    // Alpha is part of the verification key, generated during trusted setup.
    // It's a point on the G1 curve (2 coordinates: x, y).
    uint256 internal constant ALPHA_X = 1;  // PLACEHOLDER — replace with real value from trusted setup
    uint256 internal constant ALPHA_Y = 2;  // PLACEHOLDER — replace with real value from trusted setup

    // --- Beta point (G2) ---
    // Beta is a point on the G2 curve (twist of BN254).
    // G2 points have 2 coordinates, each of which is an element of Fp2 (a quadratic extension field).
    // So each coordinate has 2 components: (x_imag, x_real) and (y_imag, y_real).
    uint256 internal constant BETA_X1 = 1;  // PLACEHOLDER — x coordinate, imaginary part
    uint256 internal constant BETA_X2 = 2;  // PLACEHOLDER — x coordinate, real part
    uint256 internal constant BETA_Y1 = 1;  // PLACEHOLDER — y coordinate, imaginary part
    uint256 internal constant BETA_Y2 = 2;  // PLACEHOLDER — y coordinate, real part

    // --- Gamma point (G2) ---
    // Gamma is used in the verification equation for the public input accumulator.
    uint256 internal constant GAMMA_X1 = 1; // PLACEHOLDER — x coordinate, imaginary part
    uint256 internal constant GAMMA_X2 = 2; // PLACEHOLDER — x coordinate, real part
    uint256 internal constant GAMMA_Y1 = 1; // PLACEHOLDER — y coordinate, imaginary part
    uint256 internal constant GAMMA_Y2 = 2; // PLACEHOLDER — y coordinate, real part

    // --- Delta point (G2) ---
    // Delta is used in the verification equation for the proof element C.
    uint256 internal constant DELTA_X1 = 1; // PLACEHOLDER — x coordinate, imaginary part
    uint256 internal constant DELTA_X2 = 2; // PLACEHOLDER — x coordinate, real part
    uint256 internal constant DELTA_Y1 = 1; // PLACEHOLDER — y coordinate, imaginary part
    uint256 internal constant DELTA_Y2 = 2; // PLACEHOLDER — y coordinate, real part

    // ========================================================================
    // CONSTANTS — IC (Input Commitment) POINTS
    // ========================================================================
    // IC points are G1 points used to compute the public input accumulator.
    // There are NUM_PUBLIC_INPUTS + 1 IC points (IC[0] is the base, IC[1..N]
    // correspond to each public input).
    //
    // The accumulator is computed as:
    //   vk_x = IC[0] + input[0] * IC[1] + input[1] * IC[2] + ... + input[N-1] * IC[N]
    //
    // This linear combination binds the public inputs to the verification.
    // ========================================================================

    // IC[0] — base point (no associated public input)
    uint256 internal constant IC0_X = 1;    // PLACEHOLDER
    uint256 internal constant IC0_Y = 2;    // PLACEHOLDER

    // IC[1] — corresponds to public input [0]: validatorSetHash
    uint256 internal constant IC1_X = 1;    // PLACEHOLDER
    uint256 internal constant IC1_Y = 2;    // PLACEHOLDER

    // IC[2] — corresponds to public input [1]: blockHash
    uint256 internal constant IC2_X = 1;    // PLACEHOLDER
    uint256 internal constant IC2_Y = 2;    // PLACEHOLDER

    // IC[3] — corresponds to public input [2]: blockNumber
    uint256 internal constant IC3_X = 1;    // PLACEHOLDER
    uint256 internal constant IC3_Y = 2;    // PLACEHOLDER

    // IC[4] — corresponds to public input [3]: stateRoot
    uint256 internal constant IC4_X = 1;    // PLACEHOLDER
    uint256 internal constant IC4_Y = 2;    // PLACEHOLDER

    // ========================================================================
    // STRUCTS
    // ========================================================================

    /// @notice A Groth16 proof consists of three curve points: A (G1), B (G2), C (G1).
    /// @dev These are generated by the prover (off-chain ZK circuit runner).
    ///      The verifier checks: e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
    struct Proof {
        uint256[2] a;       // G1 point A: [x, y]
        uint256[2][2] b;    // G2 point B: [[x_imag, x_real], [y_imag, y_real]]
        uint256[2] c;       // G1 point C: [x, y]
    }

    // ========================================================================
    // EXTERNAL FUNCTIONS
    // ========================================================================

    /// @notice Verifies a Groth16 proof against the hardcoded verification key.
    /// @dev This is the main entry point. Gas cost is ~200-300k depending on
    ///      the number of public inputs (dominated by the pairing check).
    /// @param proof The Groth16 proof (A, B, C points).
    /// @param publicInputs The public inputs to the circuit.
    ///        Must have exactly NUM_PUBLIC_INPUTS elements.
    ///        [0] = validatorSetHash, [1] = blockHash, [2] = blockNumber, [3] = stateRoot
    /// @return valid True if the proof verifies correctly.
    function verifyProof(
        Proof calldata proof,                   // The ZK proof to verify
        uint256[NUM_PUBLIC_INPUTS] calldata publicInputs  // The circuit's public inputs
    ) external view returns (bool valid) {
        // Step 1: Validate that all public inputs are within the scalar field.
        // Inputs outside the field would break the verification equation.
        for (uint256 i; i < NUM_PUBLIC_INPUTS; ++i) {
            // Each input must be less than the scalar field order.
            // If not, the proof is malformed or the prover is malicious.
            if (publicInputs[i] >= SCALAR_FIELD_ORDER) {
                revert Groth16Verifier__InvalidInputCount();
            }
        }

        // Step 2: Compute the public input accumulator (vk_x).
        // vk_x = IC[0] + publicInputs[0] * IC[1] + publicInputs[1] * IC[2] + ...
        // This binds the specific public inputs to the verification.

        // Start with IC[0] as the base point.
        uint256 vkX = IC0_X;
        uint256 vkY = IC0_Y;

        // Accumulate: vk_x += publicInputs[0] * IC[1]
        (uint256 mulX, uint256 mulY) = _scalarMul(IC1_X, IC1_Y, publicInputs[0]);
        (vkX, vkY) = _pointAdd(vkX, vkY, mulX, mulY);

        // Accumulate: vk_x += publicInputs[1] * IC[2]
        (mulX, mulY) = _scalarMul(IC2_X, IC2_Y, publicInputs[1]);
        (vkX, vkY) = _pointAdd(vkX, vkY, mulX, mulY);

        // Accumulate: vk_x += publicInputs[2] * IC[3]
        (mulX, mulY) = _scalarMul(IC3_X, IC3_Y, publicInputs[2]);
        (vkX, vkY) = _pointAdd(vkX, vkY, mulX, mulY);

        // Accumulate: vk_x += publicInputs[3] * IC[4]
        (mulX, mulY) = _scalarMul(IC4_X, IC4_Y, publicInputs[3]);
        (vkX, vkY) = _pointAdd(vkX, vkY, mulX, mulY);

        // Step 3: Perform the pairing check.
        // The Groth16 verification equation is:
        //   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        //
        // Which is equivalent to checking that the product of pairings equals
        // the identity element of the target group GT.
        //
        // We negate A (flip the y-coordinate) to move it to the left side:
        //   e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        // becomes:
        //   e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        //
        // The precompile checks if the product of all pairings equals 1.

        valid = _verifyPairing(
            proof.a,        // G1 point A (will be negated inside _verifyPairing)
            proof.b,        // G2 point B
            proof.c,        // G1 point C
            vkX,            // Accumulated public input point (x-coordinate)
            vkY             // Accumulated public input point (y-coordinate)
        );
    }

    // ========================================================================
    // INTERNAL FUNCTIONS — ELLIPTIC CURVE OPERATIONS
    // ========================================================================

    /// @notice Performs scalar multiplication on a G1 point using the ecMul precompile.
    /// @dev Calls precompile at address 0x07.
    ///      Input: 96 bytes (point x, point y, scalar)
    ///      Output: 64 bytes (result x, result y)
    /// @param x The x-coordinate of the G1 point.
    /// @param y The y-coordinate of the G1 point.
    /// @param scalar The scalar to multiply by (must be < SCALAR_FIELD_ORDER).
    /// @return rx The x-coordinate of the resulting point.
    /// @return ry The y-coordinate of the resulting point.
    function _scalarMul(
        uint256 x,          // G1 point x-coordinate
        uint256 y,          // G1 point y-coordinate
        uint256 scalar      // The scalar multiplier
    ) internal view returns (uint256 rx, uint256 ry) {
        // Prepare the input for the ecMul precompile.
        // Format: [point.x (32 bytes), point.y (32 bytes), scalar (32 bytes)]
        uint256[3] memory input;
        input[0] = x;      // G1 point x-coordinate
        input[1] = y;      // G1 point y-coordinate
        input[2] = scalar;  // The scalar to multiply by

        // Call the ecMul precompile at address 0x07.
        // staticcall is used because this is a pure computation (no state changes).
        bool success;
        uint256[2] memory result;

        // solhint-disable-next-line no-inline-assembly
        assembly {
            // staticcall(gas, to, inputOffset, inputSize, outputOffset,utSize)
            // - gas: forward all remaining gas
            // - to: 0x07 (ecMul precompile address)
            // - inputOffset: pointer to input array data (skip 32-byte length prefix)
            // - inputSize: 96 bytes (3 * 32 bytes)
            // - outputOffset: pointer to result array data
            // - outputSize: 64 bytes (2 * 32 bytes)
            success := staticcall(
                gas(),          // Forward all available gas to the precompile
                0x07,           // ecMul precompile address
                input,          // Pointer to input data
                96,             // put size: 3 uint256 values = 96 bytes
                result,         // Pointer to output buffer
                64              // Output size: 2 uint256 values = 64 bytes
            )
        }

        // If the precompile call failed, revert with a descriptive error.
        if (!success) {
            revert Groth16Verifier__ScalarMulFailed();
        }

        // Return the resulting G1 point coordinates.
        rx = result[0];     // Result x-coordinate
        ry = result[1];     // Result y-coordinate
    }

    /// @notice Performs point addition on two G1 points using the ecAdd precompile.
    /// @dev Calls precompile at address 0x06.
    ///      Input: 128 bytes (point1.x, point1.y, point2.x, point2.y)
    ///      Output: 64 bytes (result.x, result.y)
    /// @param x1 The x-coordinate of the first G1 point.
    /// @param y1 The y-coordinate of the first G1 point.
    /// @param x2 The x-coordinate of the second G1 point.
    /// @param y2 The y-coordinate of the second G1 point.
    /// @return rx The x-coordinate of the resulting point.
    /// @return ry The y-coordinate of the resulting point.
    function _pointAdd(
        uint256 x1,         // First point x-coordinate
        uint256 y1,         // First point y-coordinate
        uint256 x2,         // Second point x-coordinate
        uint256 y2          // Second point y-coordinate
    ) internal view returns (uint256 rx, uint256 ry) {
        // Prepare the input for the ecAdd precompile.
        // Format: [p1.x, p1.y, p2.x, p2.y] — each 32 bytes
        uint256[4] memory input;
        input[0] = x1;     // First point x
        input[1] = y1;     // First point y
        input[2] = x2;     // Second point x
        input[3] = y2;     // Second point y

        // Call the ecAdd precompile at address 0x06.
        bool success;
        uint256[2] memory result;

        // solhint-disable-next-line no-inline-assembly
        assembly {
            // staticcall to ecAdd precompile at address 0x06
            success := staticcall(
                gas(),          // Forward all available gas
                0x06,           // ecAdd precompile address
                input,          // Pointer to input data
                128,            // Input size: 4 uint256 values = 128 bytes
                result,         // Pointer to output buffer
                64              // Output size: 2 uint256 values = 64 bytes
            )
        }

        // If the precompile call failed, revert.
        if (!success) {
            revert Groth16Verifier__PointAdditionFailed();
        }

        // Return the resulting point.
        rx = result[0];     // Result x-coordinate
        ry = result[1];     // Result y-coordinate
    }

    /// @notice Performs the final pairing check using the ecPairing precompile.
    /// @dev Calls precompile at address 0x08.
    ///      The pairing check verifies:
    ///        e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
    ///      The precompile returns 1 if the product of pairings equals 1, else 0.
    /// @param a The G1 proof point A [x, y].
    /// @param b The G2 proof point B [[x_imag, x_real], [y_imag, y_real]].
    /// @param c The G1 proof point C [x, y].
    /// @param vkX The x-coordinate of the public input accumulator point.
    /// @param vkY The y-coordinate of the public input accumulator point.
    /// @return valid True if the pairing check passes.
    function _verifyPairing(
        uint256[2] calldata a,          // Proof point A (G1)
        uint256[2][2] calldata b,       // Proof point B (G2)
        uint256[2] calldata c,          // Proof point C (G1)
        uint256 vkX,                    // Public input accumulator x
        uint256 vkY                     // Public input accumulator y
    ) internal view returns (bool valid) {
        // The ecPairing precompile takes pairs of (G1, G2) points.
        // We need 4 pairs for the Groth16 verification equation:
        //   Pair 1: (-A, B)           — the proof
        //   Pair 2: (alpha, beta)     — verification key constant
        //   Pair 3: (vk_x, gamma)     — public input binding
        //   Pair 4: (C, delta)        — the proof

        // Each pair is 6 uint256 values: G1.x, G1.y, G2.x_imag, G2.x_real, G2.y_imag, G2.y_real
        // Total: 4 pairs * 6 values = 24 uint256 values = 768 bytes
        uint256[24] memory input;

        // --- Pair 1: (-A, B) ---
        // Negate A by computing (A.x, PRIME_Q - A.y) — this flips the point over the x-axis.
        // This is equivalent to computing -A in the elliptic curve group.
        input[0] = a[0];                               // -A.x = A.x (x doesn't change)
        input[1] = (PRIME_Q - (a[1] % PRIME_Q)) % PRIME_Q; // -A.y = p - A.y (negate y mod p)
        input[2] = b[0][0];                            // B.x imaginary component
        input[3] = b[0][1];                            // B.x real component
        input[4] = b[1][0];                            // B.y imaginary component
        input[5] = b[1][1];                            // B.y real component

        // --- Pair 2: (alpha, beta) ---
        // These are verification key constants from the trusted setup.
        input[6] = ALPHA_X;                             // alpha.x
        input[7] = ALPHA_Y;                             // alpha.y
        input[8] = BETA_X1;                             // beta.x imaginary
        input[9] = BETA_X2;                             // beta.x real
        input[10] = BETA_Y1;                            // beta.y imaginary
        input[11] = BETA_Y2;                            // beta.y real

        // --- Pair 3: (vk_x, gamma) ---
        // vk_x is the accumulated public input point computed earlier.
        input[12] = vkX;                                // vk_x.x (public input accumulator)
        input[13] = vkY;                                // vk_x.y
        input[14] = GAMMA_X1;                           // gamma.x imaginary
        input[15] = GAMMA_X2;                           // gamma.x real
        input[16] = GAMMA_Y1;                           // gamma.y imaginary
        input[17] = GAMMA_Y2;                           // gamma.y real

        // --- Pair 4: (C, delta) ---
        // C is the third proof element.
        input[18] = c[0];                               // C.x
        input[19] = c[1];                               // C.y
        input[20] = DELTA_X1;                           // delta.x imaginary
        input[21] = DELTA_X2;                           // delta.x real
        input[22] = DELTA_Y1;                           // delta.y imaginary
        input[23] = DELTA_Y2;                           // delta.y real

        // Call the ecPairing precompile at address 0x08.
        // It returns a single uint256: 1 if the pairing check passes, 0 otherwise.
        uint256[1] memory result;
        bool success;

        // solhint-disable-next-line no-inline-assembly
        assembly {
            // staticcall to ecPairing precompile at address 0x08
            success := staticcall(
                gas(),          // Forward all available gas (pairing is expensive: ~100k+ gas)
                0x08,           // ecPairing precompile address
                input,          // Pointer to the 24 uint256 values
                768,            // Input size: 24 * 32 = 768 bytes
                result,         // Pointer to output (single uint256)
                32              // Output size: 1 uint256 = 32 bytes
            )
        }

        // If the precompile call itself failed (e.g., out of gas, invalid points).
        if (!success) {
            revert Groth16Verifier__PairingFailed();
        }

        // The precompile returns 1 if the pairing equation holds, 0 otherwise.
        valid = result[0] == 1;
    }
}
